src/recipe_project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static
from .views import login_view, logout_view, search_view, aboutMe_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recipes.urls')),   
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('search/', search_view, name='search'),
    path('aboutme/', aboutMe_view, name='about'),
    ]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/recipes/urls.py
from django.urls import path
from .views import home, RecipeListView, RecipeDetailView, search, aboutMe

app_name = 'recipes'

urlpatterns = [
   path('', home),
   path('list/', RecipeListView.as_view(), name="list"),
   path('list/<pk>', RecipeDetailView.as_view(), name='detail'),
   path('search/', search),
   path('aboutme/', aboutMe)
]

src/recipes/models.py
from django.db import models
from django.shortcuts import reverse

class Recipes(models.Model):
  pic = models.ImageField(upload_to='recipes', default='no_picture.jpg')
  name = models.CharField(max_length = 80)
  description = models.TextField(default='')
  cooking_time = models.IntegerField()
  ingredients = models.TextField()

  def calculate_difficulty(self):
    ingredients = self.ingredients.split(', ')
    if self.cooking_time < 10 and len(ingredients) < 4:
        difficulty = 'Easy'
    elif self.cooking_time < 10 and len(ingredients) >= 4:
        difficulty = 'Medium'
    elif self.cooking_time >= 10 and len(ingredients) < 4:
        difficulty = 'Intermediate'
    elif self.cooking_time >= 10 and len(ingredients) >= 4:
        difficulty = 'Hard'
    return difficulty


  def get_absolute_url(self):
    return reverse ('recipes:detail', kwargs={'pk': self.pk})

  def __str__(self):
    returnstring = f"name: {self.name}, description: {self.description}, cooking time: {self.cooking_time}, ingredients: {self.ingredients}"
    return str(returnstring)

src/recipes/forms.py
from django import forms

CHART__CHOICES = (         
   ('#1', 'Bar chart'),    
   ('#2', 'Pie chart'),
   ('#3', 'Line chart')
   )

class RecipeSearchForm(forms.Form): 
   name = forms.CharField(max_length = 80)
   chart_type = forms.ChoiceField(choices=CHART__CHOICES)

src/recipe_project/views.py
from django.shortcuts import render, redirect  
from django.contrib.auth import authenticate, login, logout 
from django.contrib.auth.forms import AuthenticationForm  



def login_view(request):                                
  error_message = None                             
  form = AuthenticationForm()  

  if request.method == 'POST':                        
    form = AuthenticationForm(data=request.POST)

  if form.is_valid():                                
    username = form.cleaned_data.get('username')      
    password = form.cleaned_data.get('password')

    user=authenticate(username=username, password=password)
    if user is not None:                    
      login(request, user)                
      return redirect('/list') 
  else:                                             
    error_message ='Something went wrong. Try again!'

  context ={                                             
    'form': form,                                
    'error_message': error_message 
  } 

  return render(request, 'auth/login.html', context) 

def logout_view(request):
  logout(request)
  return render(request, 'auth/success.html')    

def search_view(request):
  search(request)
  return render(request, 'recipes/search.html' )

def aboutMe_view(request):
  aboutMe(request)
  return render(request, 'recipes/about_me.html')

src/recipes/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from .models import Recipes
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import RecipeSearchForm
import pandas as pd
from .utils import get_chart


# Create your views here.
def aboutMe(request):
  return render(request, 'recipes/about_me.html')

def home(request):
  return render(request, 'recipes/recipes_home.html')

class RecipeListView(LoginRequiredMixin, ListView):
  model = Recipes
  template_name = 'recipes/main.html'

class RecipeDetailView(LoginRequiredMixin, DetailView):                       
  model = Recipes                                     
  template_name = 'recipes/detail.html' 


def search(request):
  form = RecipeSearchForm(request.POST or None)
  recipes_df = None
  chart = None
  qs = None

  if request.method =='POST':
    input = request.POST.get('name')
    chart_type = request.POST.get('chart_type')
    
    qs = Recipes.objects.filter(name__contains=input)
    if not qs:
      qs = Recipes.objects.filter(ingredients__contains=input)
    if qs:
        print(qs.values())
        recipes_df = pd.DataFrame(qs.values())
        print(recipes_df.loc[:,'name'])
        print("Column Names:", recipes_df.columns)

        chart = get_chart(chart_type, recipes_df, labels = recipes_df['name'].values)
        recipes_df = recipes_df.to_html()
    

  context = {
             'form': form,
             'objects': qs,
             'chart': chart,
             }
  
  return render(request, 'recipes/search.html', context)

src/recipes/templates/recipes/about_me.html
<!DOCTYPE html>

  <head>
    <title>Cook with Us!</title>
    {% load static %}
    <style type="text/css">
      body {
        background-color: beige;
        background-size: cover;
        display: flex;
        align-items: center;
        flex-direction: column;
        margin-top: 60px;
      }
    </style>
      <h1> Hi there, </h1>
  </head>

  <body>
    <p>It is nice to see you here!</p>
    <p>This recipe application was completed as part of my course with CareerFoundry. It isn't my best styling work (as you can probably see) but rather, showcases my journey learning Django and Python. </p>
    <p>Enjoy exploring! </p>
    <p>Feel free to reach out and connect on LinkedIn! I am always eager to see how I can improve my code or just chat :)</p>
    <a href="https://www.linkedin.com/in/gabrielle-meek-332b301b2/" target="_blank">
      <img src="{% static 'recipes/images/linkedin_icon.svg' %}" alt="LinkedIn icon"/>
    </a>
  </body>

src/recipes/templates/recipes/detail.html
<!DOCTYPE html>

  <head>
    <title>Cook with us!</title>
    <style type="text/css">
      body {
        background-color: rgb(253, 252, 225);
        display: flex;
        align-items: center;
        flex-direction: column;
        margin-top: 60px;
         }
    </style>
  </head>

  <body>
    <h2>{{object.name}}</h2>
    <img src="{{object.pic.url}}" width="200" height="300" /> 
    <br>
    <b>Name:</b>{{object.name}}<br>
    <b>Description: </b>{{object.description}}<br>
    <b>Cooking Time: </b>{{object.cooking_time}}<br>
    <b>Ingredients: </b>{{object.ingredients}}<br>
    <b>Difficulty: </b>{{object.calculate_difficulty}}<br>
  </body>

</html>

src/recipes/templates/recipes/main.html
<!DOCTYPE html>

<html>
   
   <head> 
      <title>Cook with Us!</title>
      {% load static %}
      <style type="text/css">
         body {
            background: url("{% static 'recipes/images/homepage.jpg' %}") no-repeat fixed;
            background-size: cover;
            display: flex;
            align-items: center;
            flex-direction: column;
            margin-top: 60px;
         }
         table td {
            background-color: #fffff0;
            border: none;
         }
         h1 {
            font-size: 100px;
            color: rgb(220, 216, 152);
         }
         a {
            text-decoration: none;
            color: black;
         }
        </style>
   </head>
   
   <body>
    <h1 style="text-align:center">RECIPES</h1>
    <h3 style="text-align:center" ><a href ="{%url 'logout' %}" > Logout </a></h3>
    <h3 style="text-align:center" ><a href ="{%url 'search' %}" > Search for a Recipe </a></h3>
   
    <table border="0" cellpadding="12" cellspacing = "12">   
       {% for object in object_list %} 
       <tr>
         <td style="width: 50%">
            <a href="{{object.get_absolute_url}}"> {{object.name}}</a></td>
         <td style="width: 50%">
            <img src="{{object.pic.url}}" width="150" height="200" /></td>   
       </tr>
       {% endfor %}
    </table>


   </body>
</html>

src/recipes/templates/recipes/recipes_home.html
<!DOCTYPE html>

<html>
   
   <head> 
      <title>Cook with Us!</title>
      {% load static %}
      <style type="text/css">
      body {
            background: url("{% static 'recipes/images/homepage.jpg' %}") no-repeat fixed;
            background-size: cover;
            display: flex;
            align-items: center;
            flex-direction: column;
            margin-top: 60px;
        }
        </style>
   </head>
   
   <body>
      <h1 >RECIPES</h1>
      <br>
      <a href = "{%url 'login' %}"> login </a>
   </body>
</html>

src/recipes/templates/recipes/search.html
<!DOCTYPE html>

<html lang="en">

   <head>
      <title>Cook with Us!</title>
      <h1> Search for a Recipe or Ingredient </h1>
      <h4><a href ="{%url 'recipes:list' %}" > Back to Recipes</a></h4>
      <hr>
      <style type="text/css">
         body {
           background-color: rgb(253, 252, 225);
            background-size: cover;
            display: flex;
            align-items: center;
            flex-direction: column;
            margin-top: 60px;
         }
      </style>
   </head>

   <body>
      <form action="" method="POST">
      {% csrf_token %}
      {{form}}
      <button type="submit" >search</button>
      </form> 
      <br>

      {% if objects %}
      <table border="1" cellpadding="5" cellspacing = "5">   
      <tr> 
         <td>Recipes</td>   
      </tr>
         {% for object in objects %} 
      <tr>
         <td><a href="{{object.get_absolute_url}}"> {{object.name}}</a></td>
         <td><img src="{{object.pic.url}}" width="150" height="200" /></td>   
         <td>Ingredients: {{object.ingredients}}</td>
         <td>Cooking time: {{object.cooking_time}} minutes </td>
      </tr>
         {% endfor %}
      </table>
      <br>
         <img src="data:image/jpg;base64, {{chart|safe}}">
         {% else %}
         <h3> no data</h3>
         {% endif %}
   </body>


</html>